name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: todo-0.0.1.jar
      #     path: target/todo-0.0.1.jar

      - uses: actions/checkout@v2 #
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: redtodo
          heroku_email: v.yashwanthreddy2@gmail.com

          # procfile: "web: java -jar -Djava.version=21 target/todo-0.0.1.jar"
          # branch: main
